const Poem = `
I can go birding (#ChristianCooper)
I can go jogging (#AmaudArbery)
I can relax in the comfort of my own home (#bothamjean and #AtatianaJefferson)
I can ask for help after being in a car crash (#JonathanFerrell and #RenishaMcBride)
I can have a cellphone (StephonClark)
I can leave a party to get to safety (JordanEdwards)
I can play loud music (JordanDavis)
I can sell CDs (AltonSterling)
I can sleep (AiyanaJones)
I can walk from the corner store (MikeBrown)
I can play cops and robbers (TamirRice)
I can go to church (Charleston9)
I can walk home with Skittles (TrayvonMartin)
I can hold a hair brush while leaving my own bachelor party (SeanBell)
I can party on New Years (OscarGrant)
I can get a normal traffic ticket (SandraBland)
I can lawfully carry a weapon (PhilandoCastile)
I can break down on a public road with car problems (CoreyJones)
I can shop at Walmart (JohnCrawford)
I can have a disabled vehicle (TerrenceCrutcher)
I can read a book in my own car (KeithScott)
I can be a 10yr old walking with our grandfather (#CliffordGlover)
I can decorate for a party (#ClaudeReese)
I can ask a cop a question (#RandyEvans)
I can cash a check in peace (#YvonneSmallwood)
I can take out my wallet (#AmadouDiallo)
I can run (#WalterScott)
I can breathe (#EricGarner)
I can live (#FreddieGray)
I CAN BE ARRESTED WITHOUT THE FEAR OF BEING MURDERED (#GeorgeFloyd)
White privilege is real. Take a minute to consider a Black person’s experience today. #BlackLivesMatter
*I copied and pasted this ... please do the same.
`

export default Poem;